package com.xoa.dao.product;

import com.xoa.model.product.ProductBrandModel;
import java.util.List;


public interface ProductBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_unit
     *
     * @mbggenerated
     */
    int countByExample(ProductBrandModel productModel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_unit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_unit
     *
     * @mbggenerated
     */
    int insert(ProductBrandModel productModel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_unit
     *
     * @mbggenerated
     */
    List<ProductBrandModel> selectByExample(ProductBrandModel productModel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_unit
     *
     * @mbggenerated
     */
    ProductBrandModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_unit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductBrandModel productModel);
}