package com.xoa.dao.product;
import com.xoa.model.product.ProductUnit;
import java.util.List;
public interface ProductUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_unit
     *
     * @mbggenerated
     */
    int countByExample(ProductUnit pu);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_unit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_unit
     *
     * @mbggenerated
     */
    int insert(ProductUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_unit
     *
     * @mbggenerated
     */
    List<ProductUnit> selectByExample(ProductUnit productunit);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_unit
     *
     * @mbggenerated
     */
    ProductUnit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_unit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductUnit record);
}