package com.xoa.model.inventory;

import com.xoa.model.base.PageModel;

import java.util.Date;

public class InventoryModel  extends PageModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.pname
     *
     * @mbggenerated
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.pbid
     *
     * @mbggenerated
     */
    private Integer pbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.costprice
     *
     * @mbggenerated
     */
    private Float costprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.sellingprice
     *
     * @mbggenerated
     */
    private Float sellingprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.warehouseid
     *
     * @mbggenerated
     */
    private Integer warehouseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    private String productbrandname;
    private String warehousename;


    public String getProductbrandname() {
        return productbrandname;
    }

    public void setProductbrandname(String productbrandname) {
        this.productbrandname = productbrandname;
    }

    public String getWarehousename() {
        return warehousename;
    }

    public void setWarehousename(String warehousename) {
        this.warehousename = warehousename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.id
     *
     * @return the value of inventory.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.id
     *
     * @param id the value for inventory.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.pid
     *
     * @return the value of inventory.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.pid
     *
     * @param pid the value for inventory.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.pname
     *
     * @return the value of inventory.pname
     *
     * @mbggenerated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.pname
     *
     * @param pname the value for inventory.pname
     *
     * @mbggenerated
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.pbid
     *
     * @return the value of inventory.pbid
     *
     * @mbggenerated
     */
    public Integer getPbid() {
        return pbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.pbid
     *
     * @param pbid the value for inventory.pbid
     *
     * @mbggenerated
     */
    public void setPbid(Integer pbid) {
        this.pbid = pbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.num
     *
     * @return the value of inventory.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.num
     *
     * @param num the value for inventory.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.costprice
     *
     * @return the value of inventory.costprice
     *
     * @mbggenerated
     */
    public Float getCostprice() {
        return costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.costprice
     *
     * @param costprice the value for inventory.costprice
     *
     * @mbggenerated
     */
    public void setCostprice(Float costprice) {
        this.costprice = costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.sellingprice
     *
     * @return the value of inventory.sellingprice
     *
     * @mbggenerated
     */
    public Float getSellingprice() {
        return sellingprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.sellingprice
     *
     * @param sellingprice the value for inventory.sellingprice
     *
     * @mbggenerated
     */
    public void setSellingprice(Float sellingprice) {
        this.sellingprice = sellingprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.warehouseid
     *
     * @return the value of inventory.warehouseid
     *
     * @mbggenerated
     */
    public Integer getWarehouseid() {
        return warehouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.warehouseid
     *
     * @param warehouseid the value for inventory.warehouseid
     *
     * @mbggenerated
     */
    public void setWarehouseid(Integer warehouseid) {
        this.warehouseid = warehouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.createtime
     *
     * @return the value of inventory.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.createtime
     *
     * @param createtime the value for inventory.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.createuser
     *
     * @return the value of inventory.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.createuser
     *
     * @param createuser the value for inventory.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}