package com.xoa.model.product;

import com.xoa.model.base.PageModel;

import java.util.Date;

public class ProductBrandModel extends PageModel{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_brand.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_brand.bid
     *
     * @mbggenerated
     */
    private String bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_brand.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_brand.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_brand.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_brand.baddress
     *
     * @mbggenerated
     */
    private String baddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_brand.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_brand.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_brand.id
     *
     * @return the value of product_brand.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_brand.id
     *
     * @param id the value for product_brand.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_brand.bid
     *
     * @return the value of product_brand.bid
     *
     * @mbggenerated
     */
    public String getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_brand.bid
     *
     * @param bid the value for product_brand.bid
     *
     * @mbggenerated
     */
    public void setBid(String bid) {
        this.bid = bid == null ? null : bid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_brand.name
     *
     * @return the value of product_brand.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_brand.name
     *
     * @param name the value for product_brand.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_brand.create_user
     *
     * @return the value of product_brand.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_brand.create_user
     *
     * @param createUser the value for product_brand.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_brand.create_time
     *
     * @return the value of product_brand.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_brand.create_time
     *
     * @param createTime the value for product_brand.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_brand.baddress
     *
     * @return the value of product_brand.baddress
     *
     * @mbggenerated
     */
    public String getBaddress() {
        return baddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_brand.baddress
     *
     * @param baddress the value for product_brand.baddress
     *
     * @mbggenerated
     */
    public void setBaddress(String baddress) {
        this.baddress = baddress == null ? null : baddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_brand.tel
     *
     * @return the value of product_brand.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_brand.tel
     *
     * @param tel the value for product_brand.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_brand.remark
     *
     * @return the value of product_brand.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_brand.remark
     *
     * @param remark the value for product_brand.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}