package com.xoa.model.warehouse;

import com.xoa.model.base.PageModel;

import java.util.Date;

public class WareHouseModel extends PageModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_warehouse.wid
     *
     * @mbggenerated
     */
    private Integer wid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_warehouse.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_warehouse.wnum
     *
     * @mbggenerated
     */
    private String wnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_warehouse.wname
     *
     * @mbggenerated
     */
    private String wname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_warehouse.manage_user
     *
     * @mbggenerated
     */
    private String manageUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_warehouse.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_warehouse.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_warehouse.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_warehouse.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_warehouse.wid
     *
     * @return the value of erp_warehouse.wid
     *
     * @mbggenerated
     */
    public Integer getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_warehouse.wid
     *
     * @param wid the value for erp_warehouse.wid
     *
     * @mbggenerated
     */
    public void setWid(Integer wid) {
        this.wid = wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_warehouse.type
     *
     * @return the value of erp_warehouse.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_warehouse.type
     *
     * @param type the value for erp_warehouse.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_warehouse.wnum
     *
     * @return the value of erp_warehouse.wnum
     *
     * @mbggenerated
     */
    public String getWnum() {
        return wnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_warehouse.wnum
     *
     * @param wnum the value for erp_warehouse.wnum
     *
     * @mbggenerated
     */
    public void setWnum(String wnum) {
        this.wnum = wnum == null ? null : wnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_warehouse.wname
     *
     * @return the value of erp_warehouse.wname
     *
     * @mbggenerated
     */
    public String getWname() {
        return wname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_warehouse.wname
     *
     * @param wname the value for erp_warehouse.wname
     *
     * @mbggenerated
     */
    public void setWname(String wname) {
        this.wname = wname == null ? null : wname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_warehouse.manage_user
     *
     * @return the value of erp_warehouse.manage_user
     *
     * @mbggenerated
     */
    public String getManageUser() {
        return manageUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_warehouse.manage_user
     *
     * @param manageUser the value for erp_warehouse.manage_user
     *
     * @mbggenerated
     */
    public void setManageUser(String manageUser) {
        this.manageUser = manageUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_warehouse.address
     *
     * @return the value of erp_warehouse.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_warehouse.address
     *
     * @param address the value for erp_warehouse.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_warehouse.create_user
     *
     * @return the value of erp_warehouse.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_warehouse.create_user
     *
     * @param createUser the value for erp_warehouse.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_warehouse.create_date
     *
     * @return the value of erp_warehouse.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_warehouse.create_date
     *
     * @param createDate the value for erp_warehouse.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_warehouse.remark
     *
     * @return the value of erp_warehouse.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_warehouse.remark
     *
     * @param remark the value for erp_warehouse.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}